info:
  component: '@app.name@'

server:
  port: '@port@'

spring:
  application:
    name: '@app.name@'
  jersey:
    type: filter
  datasource:
    platform: mysql
    jdbcUrl: '@database.url@'
    username: '@database.username@'
    password: '@database.password@'
    driverClassName: '@database.driverclass@'
    hikari:
      idleTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 15
      connectionTimeout: 30000
      poolName: nextsms-api-pool
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: '@database.dialect@'
    show-sql: '@database.showsql@'
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: none
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    enabled: false
    registryFetchIntervalSeconds: 5

applicationConfig:
  applicationName: '@app.name@'
  environment: '@environment@'
  version: '@version@'
  authTokenValidity: 7200
  apiKey: 'some_api_key'

messagesConfig:
  messageCacheSeconds: 3600

okHttpClientConfig:
  connectionTimeout: 10
  readTimeout: 60
  writeTimeout: 60

spring.jpa.hibernate.ddl-auto: update

management.endpoint.health.show-details: always