info:
  component: 'casino-webapi'

server:
  port: '${APP_PORT}'

spring:
  application:
    name: 'casino-webapi'
  jersey:
    type: filter
  datasource:
    platform: mysql
    jdbcUrl: 'jdbc:mariadb://${DB_HOST}:3306/${DB_NAME}?useSSL=false&useUnicode=true&characterEncoding=UTF-8'
    username: '${DB_USERNAME}'
    password: '${DB_PASSWORD}'
    driverClassName: 'org.mariadb.jdbc.Driver'
    hikari:
      idleTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 15
      connectionTimeout: 30000
      poolName: nextsms-api-pool
      connectionTestQuery: SELECT 1
  jpa:
    database-platform: 'org.hibernate.dialect.MariaDB102Dialect'
    show-sql: 'true'
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.id.new_generator_mappings: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: none
  jackson:
    serialization:
      indent-output: true

eureka:
  client:
    enabled: false
    registryFetchIntervalSeconds: 5

applicationConfig:
  applicationName: 'casino-webapi'
  environment: 'local'
  version: '1.0.0'
  authTokenValidity: 7200
  apiKey: 'some_api_key'

messagesConfig:
  messageCacheSeconds: 3600

okHttpClientConfig:
  connectionTimeout: 10
  readTimeout: 60
  writeTimeout: 60

spring.jpa.hibernate.ddl-auto: update

management.endpoint.health.show-details: always